controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

api_platform:
    resource: ../config/routes/api_platform.yaml

reference_show:
    path: /api-platform/reference/{id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\ReferenceController::show
        _api_resource_class: App\Entity\Reference
        _api_item_operation_name: show

reference:
    path: /api-platform/reference/
    methods: ['GET']
    defaults:
        _controller: App\Controller\ReferenceController::index
        _api_resource_class: App\Entity\Reference
        _api_item_operation_name: index      

reference_new:
    path: /api-platform/reference/new
    methods: ['POST']
    defaults:
        _controller: App\Controller\ReferenceController::new
        _api_resource_class: App\Entity\Reference
        _api_item_operation_name: new   

reference_delete:
    path: /api-platform/reference/{id}
    methods: ['DELETE']
    defaults:
        _controller: App\Controller\ReferenceController::delete
        _api_resource_class: App\Entity\Reference
        _api_item_operation_name: delete   

reference_edit:
    path: /api-platform/reference/{id}/edit
    methods: ['PUT']
    defaults:
        _controller: App\Controller\ReferenceController::edit
        _api_resource_class: App\Entity\Reference
        _api_item_operation_name: edit           

picture_new:
    path: /api-platform/public/{img}
    methods: ['GET']
    defaults:
        _controller: App\Controller\PublicController::indexImg
        _api_resource_class: App\Entity\Picture
        _api_item_operation_name: indexImg  
        
user_show:
    path: /api-platform/public/user/{id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\PublicController::userIndex
        _api_resource_class: App\Entity\User
        _api_item_operation_name: userIndex  